generate a stacktrace on crash

diff --git a/.github/workflows/build-unix.yml b/.github/workflows/build-unix.yml
--- a/.github/workflows/build-unix.yml
+++ b/.github/workflows/build-unix.yml
@@ -157,11 +157,15 @@ jobs:
           echo "CPPFLAGS=$CPPFLAGS" >> $GITHUB_ENV
           echo "LDFLAGS=$LDFLAGS" >> $GITHUB_ENV
 
-      - name: Install Linux packages
+      - name: Install Ubuntu Linux packages
         if: ${{ matrix.os == 'linux' }}
         run: |
           sudo apt update
           sudo apt install -y ant autoconf automake g++ libssl-dev afflib-tools libewf-dev libqcow-dev libvhdi-dev libvmdk-dev libmagic-dev libtool make pkg-config zlib1g-dev wget
+          echo ASAN_SYMBOLIZER_PATH=/usr/bin/llvm-symbolizer >> $GITHUB_ENV
+          echo ASAN_OPTIONS="symbolize=1:abort_on_error=1" >> $GITHUB_ENV
+
+
 
       - name: Install Mingw packages and setup for cross-compiling
         if: ${{ matrix.os == 'mingw' }}
@@ -203,14 +207,40 @@ jobs:
           make unpack
           find . -ls | grep -v '[.]git'
 
-      - name: Run make
-        run: |
-          make -j${{ steps.cores.outputs.cores }} check ${{ matrix.make_flags }} VERBOSE=1 TESTS=
-
       - name: Run make check on Mac/Linux
         if: ${{ matrix.os != 'mingw' }}
         run: |
           make -j${{ steps.cores.outputs.cores }} check ${{ matrix.make_flags }} VERBOSE=1 || result=1 ; for i in $(find test -name '*.log') ; do printf '\n%79s\n' | tr ' ' '=' ; echo "$i" ; cat "$i" ; done ; exit $result
+
+      - name: Run make check on Linux with core dump enabled
+        if: ${{ matrix.os == 'linux' }}
+        id: run_tests
+        run: |
+          set -e
+          ulimit -c unlimited
+          make -j${{ steps.cores.outputs.cores }} check ${{ matrix.make_flags }} VERBOSE=1 || echo "TEST_FAILED=1" >> $GITHUB_ENV
+
+      - name: Show core dump backtrace if tests failed
+        if: ${{ env.TEST_FAILED == '1' && matrix.os == 'linux' }}
+        run: |
+          echo "Checking for core dump..."
+          COREFILE=$(find . -type f -name 'core*' | head -n 1)
+          if [ -n "$COREFILE" ]; then
+            echo "Found core file: $COREFILE"
+            BINARY=$(file "$COREFILE" | sed -n "s/.*from '\(.*\)'.*/\1/p")
+            if [ -x "$BINARY" ]; then
+              echo "Running gdb to get backtrace..."
+              gdb -batch -ex "thread apply all bt full" -ex "quit" "$BINARY" "$COREFILE"
+            else
+              echo "Could not identify executable from core file."
+            fi
+          else
+            echo "No core file found."
+          fi
+
+      - name: Fail job if tests failed
+        if: ${{ env.TEST_FAILED == '1' }}
+        run: exit 1
 
       - name: Run make check on Mingw
         if: ${{ matrix.os == 'mingw' }}
@@ -250,14 +280,8 @@ jobs:
         if: ${{ matrix.codecov == 'yes' }}
         run: |
           make -j check V=0
-          #make -j test/fiwalk/fiwalk_test V=0
-          #make -j test/runner V=0
-
-#      - name: Run unit tests for codecov
-#        if: ${{ matrix.codecov == 'yes' }}
-#        run: |
-#          test/fiwalk/fiwalk_test -s
-#          test/runner -s
+          make -j test/fiwalk/fiwalk_test V=0
+          make -j test/runner V=0
 
       - name: run gcov
         if: ${{ matrix.codecov == 'yes' }}
